# Site settings
title: Nooga.com Election Guide
description: "There are more than 60 candidates in the Hamilton County election on Nov. 4. That's a lot of names and faces to keep straight. Our election guide cuts through the noise so you can just focus on the ones who'll be on your ballot."
image: "election-guide.jpg"

# Build settings
markdown: kramdown
permalink: pretty
ignore:
  - Gemfile
  - Gemfile.lock

# API keys
civicAPIKey: AIzaSyCR53IADo5PcbVLc2tKnWk-0bo3FskStsY
googleKey: UA-22274451-1
fb_appID: 1400280486890380

