# Site settings
title: Nooga.com Voter Guide
description: "Nooga.com voter guide for the Nov. 4 election in Hamilton County, Tennessee."
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# API keys
civicAPIKey: AIzaSyCR53IADo5PcbVLc2tKnWk-0bo3FskStsY

