# Site settings
title: Nooga.com Election Guide
description: "Nooga.com guide for the Nov. 4 election in Hamilton County, Tennessee."

# Build settings
markdown: kramdown
permalink: pretty

# API keys
civicAPIKey: AIzaSyCR53IADo5PcbVLc2tKnWk-0bo3FskStsY
googleKey: UA-22274451-1
